# Generated by Django 3.2.9 on 2021-11-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('truck_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('number_plate', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=45)),
                ('num_wheels', models.IntegerField()),
                ('truck_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_owner.truck_owner')),
            ],
        ),
    ]
