# Generated by Django 3.2.9 on 2021-11-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='driver_id',
        ),
    ]
