# Generated by Django 3.2.9 on 2021-11-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('sender_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('driver_id', models.CharField(max_length=45)),
            ],
            options={
                'unique_together': {('sender_id', 'driver_id')},
            },
        ),
    ]
